version: '3'

services:

  gauth:
    build: .
    volumes:
      - ./src:/app/src
      - ./nodemon.json:/app/nodemon.json
    command: npm run dev
    depends_on:
      - mongodb

  mongodb:
    image: mongo
    ports:
      - "27018:27018"
    command: mongod --port 27018
